site_name: Документация репозитория команды Гармония
site_url: https://harmony249.github.io/project-hse
site_description: Внутренняя документация команды Гармония

docs_dir: docs
site_dir: site

theme:
  features:
    - navigation.instant
    - navigation.instant.prefetch

nav:
  - Инструкция: index.md
  - CI/CD: ci-cd.md