site_name: Документация репозитория команды Гармония
site_url: https://harmony249.github.io/project-hse
theme:
  name: material
nav:
  - Home: index.md

repo_name: harmony249/project-hse
repo_url: https://github.com/harmony249/project-hse

theme:
  name: material
  language: ru
  palette:
    - scheme: default
      primary: indigo
      accent: blue
  features:
    - navigation.expand
    - navigation.instant
    - navigation.top
    - content.code.copy
    - search.suggest
    - search.highlight

nav:
  - Главная: index.md

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - autoreload
  - minify:
      minify_html: true

docs_dir: docs
site_dir: site